export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const GET_TOKEN_URL_SUCCESS = 'GET_TOKEN_URL_SUCCESS';
export const GET_TOKEN_URL_FAILURE = 'GET_TOKEN_URL_FAILURE';
export const SET_FETCHING_TOKEN_TRUE = 'SET_FETCHING_TOKEN_TRUE';
export const SET_FETCHING_TOKEN_FALSE = 'SET_FETCHING_TOKEN_FALSE';
export const SET_FETCHING_PICTURES_TRUE = 'SET_FETCHING_PICTURES_TRUE';
export const SET_FETCHING_PICTURES_FALSE = 'SET_FETCHING_PICTURES_FALSE';
export const SET_TOKEN_STATE_FROM_LOCALSTORAGE = 'SET_TOKEN_STATE_FROM_LOCALSTORAGE';
export const SET_INPUT_STATE_FROM_LOCALSTORAGE = 'SET_INPUT_STATE_FROM_LOCALSTORAGE';
export const SET_PICTURES_FROM_INSTA = 'SET_PICTURES_FROM_INSTA';

