export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_URL_SUCCESS = 'GET_TOKEN_URL_SUCCESS';
export const GET_TOKEN_URL_FAILURE = 'GET_TOKEN_URL_FAILURE';
export const SET_FETCHING_TOKEN_TRUE = 'SET_FETCHING_TOKEN_TRUE';
export const SET_FETCHING_TOKEN_FALSE = 'SET_FETCHING_TOKEN_FALSE';
